{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "shopdashboard.serviceAccountName" . }}
  namespace: ui
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
